version: '3.6'

services:
  smart-brain-api-1:
    container_name: backend
    # image: node:8.11.1
    build: ./
    command: npm start
    working_dir: /usr/src/smartbrain-api-1
    ports:
      - "3000:3000"
